### ISSUE TITLE
Application crash when i start it

### ISSUE THREAD

**Issue by thebiniowski** [ilkerogutcu/keydrop-giveaway-bot#1]

**Comment by thebiniowski** [comment]
I set everything in config but it doesn't work

**Comment by ilkerogutcu** [comment]
Hey, you should install dotnet from microsoft.

**Download .NET 7 from this link https://dotnet.microsoft.com/en-us/download**

**Comment by ilkerogutcu** [comment]
> I set everything in config but it doesn't work

Hey, you should install dotnet from microsoft and try again.

Download .NET 7 from this link https://dotnet.microsoft.com/en-us/download

**Comment by thebiniowski** [comment]
ty
