### ISSUE TITLE
Nie działa, - not working

### ISSUE THREAD

**Issue by KOLEGA5241** [ilkerogutcu/keydrop-giveaway-bot#10]
![Bez tytułu](https://github.com/ilkerogutcu/keydrop-giveaway-bot/assets/96379106/474d8f1f-5d1f-454d-a180-a80eda9cf47d)

z dnia na dzień, być może że north coś wykrył

overnight, perhaps the North has detected something

**Comment by thebiniowski** [comment]
pobierz nowego chromedrivera
