### ISSUE TITLE
Need Help.

### ISSUE THREAD

**Issue by Darknight7676** [ilkerogutcu/keydrop-giveaway-bot#2]
I'm new here and I am really confuse, do you mind giving me an easier tutorial to understand better on what I need and should do please? Just really confused.

**Comment by Mesharsky** [comment]
install dotnet on your windows and then run the project inside /src folder 

Intructions are very clear.

**Comment by ilkerogutcu** [comment]
> I'm new here and I am really confuse, do you mind giving me an easier tutorial to understand better on what I need and should do please? Just really confused.

Tutorial video has been added to the README.

**Comment by ilkerogutcu** [comment]
> I'm new here and I am really confuse, do you mind giving me an easier tutorial to understand better on what I need and should do please? Just really confused.

[Tutorial video](https://streamable.com/ymq8c0) added for old version.

**Comment by Darknight7676** [comment]
Alright Thank you guys, its working now.
