### ISSUE TITLE
An error occurred while getting vioShield cookie value. Please check your session id.

### ISSUE THREAD

**Issue by cocoxixihahapreto** [ilkerogutcu/keydrop-giveaway-bot#4]
i have checked and re checked everything. ive done it from the start multiple times even erasing every data, still get the same issue.
i dont know much or even anything about api so any help counts, thanks anyway

**Comment by ilkerogutcu** [comment]
I think your problem is user_agent. Can you try this:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

**Comment by cocoxixihahapreto** [comment]
same issue still, i already had that user agent tho but i still rewrote it

**Comment by ilkerogutcu** [comment]
> same issue still, i already had that user agent tho but i still rewrote it

Can you write to me via Discord?

**Comment by cocoxixihahapreto** [comment]
sure where can i send you my discord without leaking it?

**Comment by ilkerogutcu** [comment]
When you run the bot, you can see my discord ID information there.

**Comment by cocoxixihahapreto** [comment]
just added you

**Comment by ilkerogutcu** [comment]
Just to let you know guys, the problem was fixed by clearing all cookies, logging in again to Key-Drop, and getting a new session ID.
