### ISSUE TITLE
please check your id error

### ISSUE THREAD

**Issue by ulucyldz** [ilkerogutcu/keydrop-giveaway-bot#7]
![resim_2023-05-01_130412088](https://user-images.githubusercontent.com/131407643/235438500-a8ae6421-d198-408c-b7dd-43630a4a1904.png)
I keep getting an error like this, what should i do?

I already wrote my session_id.

**Comment by ilkerogutcu** [comment]
Hi, can you try this:

1. [Download last release](https://github.com/ilkerogutcu/keydrop-giveaway-bot/releases/tag/v.1.3)
2. Clear the all cookies for key-drop
3. Sign in key-drop
4. Get new session id and try this user-agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

**Comment by ulucyldz** [comment]
teşekkür ederim🙌, birde çekiliş için para alt sınırı yapabilme şansın var mı? Mesela 1 dolar altı çekilişe katılmak istemem.

thank you🙌, do you have a chance to make a lower limit of money for the giveaway? For example, I do not want to participate in the giveaway under 1 dollar.

**Comment by ilkerogutcu** [comment]
> teşekkür ederim🙌, birde çekiliş için para alt sınırı yapabilme şansın var mı? Mesela 1 dolar altı çekilişe katılmak istemem.
> 
> thank you🙌, do you have a chance to make a lower limit of money for the giveaway? For example, I do not want to participate in the giveaway under 1 dollar.

Great idea because KeyDrop has now set a limit for giveaways, I will try to add this feature today.
