### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Fergusonnn** [ilkerogutcu/keydrop-giveaway-bot#8]
Its not working, im getting an error. Same error when building myself or downloading ready bot.
![image](https://user-images.githubusercontent.com/105175668/236639418-6f0a0e8e-e8b7-4a65-80db-7ea453fe1041.png)

**Comment by vv0l1n** [comment]
same here

**Comment by ilkerogutcu** [comment]
The bot is working, but I don't understand why you're getting errors. It could be related to a setting on your computer.

**Comment by nan4k7** [comment]
It ain't working for me either... I get a 403 when trying to get vioshield

![image](https://github.com/ilkerogutcu/keydrop-giveaway-bot/assets/8295972/925106cb-5875-45de-9668-b2d2535aa39b)


PS: I triple checked and session is OK

**Comment by ilkerogutcu** [comment]
> It ain't working for me either... I get a 403 when trying to get vioshield
> 
> ![image](https://user-images.githubusercontent.com/8295972/240298663-925106cb-5875-45de-9668-b2d2535aa39b.png)
> 
> PS: I triple checked and session is OK

This error is related to Cloudflare. I don't know why some people get this error. Can you try again in incognito tab?

**Comment by ilkerogutcu** [comment]
> > It ain't working for me either... I get a 403 when trying to get vioshield
> > ![image](https://user-images.githubusercontent.com/8295972/240298663-925106cb-5875-45de-9668-b2d2535aa39b.png)
> > PS: I triple checked and session is OK
> 
> I don't know why some people get this error. Can you try again in incognito tab?

**Comment by nan4k7** [comment]
> 

nope, sessid changed but same error

**Comment by ilkerogutcu** [comment]
> > 
> 
> nope, sessid changed but same error

Can you add me on Discord? ilker#1828

**Comment by nan4k7** [comment]
> ilker#1828

done! I'm DaEMoN#5710
